"""Export service for CSV, JSON, and executive Markdown reports."""

import json
from typing import List, Dict, Any
import pandas as pd
from sqlalchemy.orm import Session
from src.database.models import Meeting, ActionItem, Decision


class ExportService:
    def __init__(self, db: Session):
        self.db = db

    def export_action_items_csv(self, meeting_id: str = None) -> str:
        """Export action items formatted as CSV string."""
        q = self.db.query(ActionItem)
        if meeting_id:
            q = q.filter(ActionItem.meeting_id == meeting_id)
        items = q.all()

        data = []
        for i in items:
            data.append({
                "Task ID": i.task_id,
                "Meeting ID": i.meeting_id,
                "Task": i.task,
                "Owner": i.owner or "Unassigned",
                "Deadline": i.deadline.strftime("%Y-%m-%d") if i.deadline else "None",
                "Original Deadline Phrasing": i.deadline_text_original or "",
                "Priority": i.priority,
                "Status": i.status,
                "Action Type": i.action_type,
                "Confidence": i.confidence,
                "Evidence": i.evidence,
                "Review Status": i.review_status,
            })

        df = pd.DataFrame(data)
        return df.to_csv(index=False)

    def export_meeting_json(self, meeting_id: str) -> str:
        """Export full meeting details, segments, action items, and decisions as JSON."""
        meeting = self.db.query(Meeting).filter(Meeting.meeting_id == meeting_id).first()
        if not meeting:
            return "{}"

        data = {
            "meeting_id": meeting.meeting_id,
            "title": meeting.title,
            "meeting_date": meeting.meeting_date.isoformat() if meeting.meeting_date else None,
            "meeting_type": meeting.meeting_type,
            "organizer": meeting.organizer,
            "participants": meeting.participants,
            "action_items": [
                {
                    "task_id": a.task_id,
                    "task": a.task,
                    "owner": a.owner,
                    "deadline": a.deadline.isoformat() if a.deadline else None,
                    "priority": a.priority,
                    "status": a.status,
                    "confidence": a.confidence,
                    "evidence": a.evidence,
                    "validation_flags": a.validation_flags,
                    "requires_review": a.requires_review,
                }
                for a in meeting.action_items
            ],
            "decisions": [
                {
                    "decision_id": d.decision_id,
                    "decision": d.decision,
                    "evidence": d.evidence,
                }
                for d in meeting.decisions
            ],
        }
        return json.dumps(data, indent=2)

    def export_meeting_markdown(self, meeting_id: str) -> str:
        """Generate an executive meeting summary in Markdown format."""
        meeting = self.db.query(Meeting).filter(Meeting.meeting_id == meeting_id).first()
        if not meeting:
            return "# Meeting Not Found"

        lines = [
            f"# Executive Meeting Summary: {meeting.title}",
            "",
            f"- **Date**: {meeting.meeting_date.strftime('%Y-%m-%d') if meeting.meeting_date else 'N/A'}",
            f"- **Type**: {meeting.meeting_type}",
            f"- **Organizer**: {meeting.organizer or 'Unspecified'}",
            f"- **Participants**: {', '.join(meeting.participants) if meeting.participants else 'None recorded'}",
            "",
            "## Key Decisions",
        ]

        if meeting.decisions:
            for d in meeting.decisions:
                lines.append(f"- **Decision**: {d.decision}")
                lines.append(f"  - *Evidence*: \"{d.evidence}\"")
        else:
            lines.append("- No explicit decisions recorded.")

        lines.extend(["", "## Action Items", ""])

        if meeting.action_items:
            lines.append("| Task | Owner | Deadline | Priority | Status | Confidence |")
            lines.append("|---|---|---|---|---|---|")
            for a in meeting.action_items:
                d_str = a.deadline.strftime("%Y-%m-%d") if a.deadline else "None"
                lines.append(
                    f"| {a.task} | {a.owner or 'Unassigned'} | {d_str} | {a.priority} | {a.status} | {a.confidence:.2f} |"
                )
        else:
            lines.append("No action items identified for this meeting.")

        lines.extend([
            "",
            "---",
            "*Report generated by AI Meeting Action-Item Extractor*",
        ])
        return "\n".join(lines)
